name: Publish Versioned Image to GHCR

concurrency:
  group: Publish Version
  cancel-in-progress: false

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * SUN"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-publish-image:
    name: Build Image and Publish to ghcr.io
    runs-on: ubuntu-latest
    environment: Publish
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.PACKAGE_PUBLISHER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          echo ${{ env.IMAGE_NAME }}
          docker --version
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@latest .
          docker push -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@latest 
          

      # - name: Extract metadata for Docker
      #   id: meta
      #   uses: docker/metadata-action@v5

      # - name: Build and Push Docker Image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
      
      # - name: Build and Push Docker Latest Image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: latest
      #     labels: ${{ steps.meta.outputs.labels }}

      # - name: Generate Artifact Attestation
      #   uses: actions/attest-build-provenance@v3
      #   with:
      #     subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      #     subject-digest: ${{ steps.meta.outputs.digest }}
      #     push-to-registry: true
