name: Publish Versioned Image to GHCR

concurrency:
  group: Publish Version
  cancel-in-progress: false

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * SUN"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-publish-image:
    name: Build Image and Publish to ghcr.io
    runs-on: ubuntu-latest
    environment: Publish
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.PACKAGE_PUBLISHER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build Docker Image
      #   run: |
      #     export TAG=$(echo "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest" | tr '[:upper:]' '[:lower:]')
      #     echo $TAG
      #     docker --version
      #     docker build -t $TAG .
      #     docker push $TAG

      - name: Build and Push Versioned Image
        run: |
          pip index versions dbt-snowflake | grep dbt-snowflake | grep -oE "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}"
          # export VERSION=$(pip index versions dbt-snowflake | grep LATEST | grep -oE "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}")
          # echo $VERSION
          # export TAG=$(echo "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$VERSION" | tr '[:upper:]' '[:lower:]')
          # echo $TAG
          # docker build -t $TAG .
          # docker push $TAG
